apiVersion: v1
kind: ServiceAccount
metadata:
  name: fitness-app-sa
  namespace: default
  annotations:
    # This Client ID tells Workload Identity which Azure Identity to assume
    # Replace the value below with the Client ID(managed identity)
    azure.workload.identity/client-id: "7355df37-dcf0-4cd8-89a9-f8eac8611a7f"
  labels:
    azure.workload.identity/use: "true"
