apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-fitness-app
  namespace: default
spec:
  provider: azure
  secretObjects:
  # This section creates a regular Kubernetes Secret from the Key Vault data
  # so that the Pod can load it into environment variables easily.
  - secretName: fitness-app-env-secret
    type: Opaque
    data:
    # 'objectName' must match the secret name in Key Vault
    # 'key' will be the name of the environment variable in Kubernetes
    - objectName: CosmosDb
      key: MONGODB_URI
    - objectName: JwtSecret
      key: JWT_SECRET
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "7355df37-dcf0-4cd8-89a9-f8eac8611a7f" # Replace with your Client ID
    keyvaultName: "ara-key" # Replace with your Key Vault name
    tenantId: "3076b773-f5d9-413e-9564-7deaa3d0d7b7" # You can get this by running: az account show --query tenantId -otsv
    objects: |
      array:
        - |
          objectName: CosmosDb
          objectType: secret
          objectVersion: ""
        - |
          objectName: JwtSecret
          objectType: secret
          objectVersion: ""
